services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: ".env"
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - $POSTGRES_DATA_PATH:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 3s
      timeout: 3s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ".env"
    ports:
      - $PGADMIN_PORT:80
    volumes:
      - $PGADMIN_DATA_PATH:/var/lib/pgadmin
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json

configs:
  servers.json:
    content: |
      {"Servers": {"1": {
        "Name": "Postgres",
        "Group": "Servers",
        "Host": "postgres",
        "Port": $POSTGRES_PORT,
        "MaintenanceDB": "postgres",
        "Username": "$POSTGRES_USER",
        "SSLMode": "prefer"
      }}}