services:
  postgres:
    image: postgres:16-alpine
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file: ".env"

networks:
  postgres: